const movies =  [
    {
        id: 'Zksf5HsKJfRG5g68e',
        title: "Star Wars, épisode V : L'Empire contre-attaque",
        synopsis: "L'univers de Star Wars se déroule dans une galaxie qui est le théâtre d'affrontements entre les Chevaliers Jedi et les Seigneurs noirs des Sith, personnes sensibles à la Force, un champ énergétique mystérieux leur procurant des pouvoirs psychiques. Les Jedi maîtrisent le Côté lumineux de la Force, pouvoir bénéfique et défensif, pour maintenir la paix dans la galaxie. Les Sith utilisent le Côté obscur, pouvoir nuisible et destructeur, pour leurs usages personnels et pour dominer la galaxie. Pour amener la paix, une République galactique a été fondée avec pour capitale la planète Coruscant. Mais, tout au long de son existence, elle est secouée par des sécessions et des guerres. Pour mettre fin à ceci, la République est remplacée en 19 av. BYNote 1 par un Empire galactique autoritaire et discriminatoire. Cette nouvelle entité est dirigée par le Sith Palpatine et son apprenti Dark Vador. Mais après plusieurs années, la brutalité du régime provoque l'apparition d'une opposition armée : l'Alliance rebelle. Sa première victoire se déroule lors de la bataille de Yavin, lorsque les rebelles parviennent à détruire l'arme absolue de l'Empire, la station spatiale Étoile noirea 1. Très contrarié par cet échec, l'empereur confie alors à son apprenti Dark Vador la tâche de traquer et d'éliminer les rebellesa.",
        img: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRj_tZqx3RJGSjsR57mEjd-A1BurIKcq2lXSVDMA2dodAvGlRM0'
    },
    {
        id: 'Fksf5sgHKJgRGg568',
        title: "La Ligne verte",
        synopsis: "En 1935, Paul Edgecombe est gardien-chef au pénitencier de Cold Mountain en Louisiane, au bloc E, surnommé La Ligne verte, où sont détenus des condamnés à la chaise électrique. Un jour, un nouveau détenu arrive. Il s'agit de John Coffey, un colosse, condamné pour le viol et le meurtre de deux sœurs. Cependant, ces faits offrent un contraste très troublant avec la douceur et la gentillesse de John qui est, semble-t-il, doté de pouvoirs surnaturels. Paul Edgecombe tient à ce que les prisonniers jouissent malgré tout d'un environnement paisible et humain. Percy Wetmore, nouveau gardien sous les ordres de Paul, perturbe cette organisation bien huilée, notamment par la cruauté et la perversité dont il fait preuve envers les détenus. Par exemple, pour passer ses nerfs, il frappe sauvagement son prisonnier souffre-douleur Édouard Delacroix et lui casse trois doigts. Mais, ni Paul ni Hall Moores, le directeur du pénitencier, ne peuvent agir contre lui, car il est « protégé » par sa famille, en particulier sa tante, dont le mari est le gouverneur de l'État de Louisiane. Paul et son équipe vont chercher un prisonnier particulièrement dangereux, William Wharton — qui se surnomme lui-même « Billy the Kid » — condamné à mort pour le meurtre de trois personnes, dont une femme enceinte, dans un braquage. Quand ils le prennent en charge, William semble anéanti, probablement drogué par une forte dose de calmants. En réalité il simule, et en arrivant dans le « bloc E », il se jette sournoisement sur le gardien Dean Stanton pour l'étrangler. Alors que Percy pourrait maîtriser William Wharton, il ne fait rien, de toute évidence tétanisé par sa lâcheté. Heureusement, les autres gardiens font preuve de plus de sang-froid et réussissent finalement à délivrer leur collègue et à maîtriser le nouveau venu.",
        img: 'https://fr.web.img4.acsta.net/medias/nmedia/18/66/15/78/19254683.jpg'
    },
    {
        id: 'Hkssf5gHKJsRG568g',
        title: "Forest Gump",
        synopsis: "Le film débute par la scène où une plume d'oiseau, volant dans les airs, atterrit aux pieds de Forrest Gump, un jeune homme simple d'esprit assis sur un banc dans la ville de Savannah en Géorgie, attendant le bus. Au fil des différents interlocuteurs qui viennent s’asseoir tour à tour à côté de lui sur le banc, Forrest Gump va raconter la fabuleuse histoire de sa vie ; à l'image de la plume (que l'on apercevra aussi à la fin du film) qui se laisse porter par le vent, Forrest se laisse porter par les événements qu'il traverse dans l'Amérique de la seconde moitié du xxe siècle. De son enfance, mis à l'écart par les enfants de son âge à cause de ses handicaps mentaux et physiques, jusqu'au moment où, devenu milliardaire, il raconte son histoire, Forrest Gump sera tour à tour champion de football américain, diplômé d'une université, soldat durant la guerre du Viêt Nam (recevant la médaille d'Honneur du Congrès), champion de ping-pong dans l'équipe militaire américaine, capitaine de crevettier, marathonien exceptionnel (courant sans s'arrêter pendant plus de trois ans) et fera la couverture du magazine Fortune. Se trouvant au cœur des principaux événements de l'histoire des États-Unis entre les années 1950 et 1980, il en devient — involontairement — l'un des acteurs décisifs, inspirant notamment au chanteur Elvis Presley sa façon de se déhancher sur scène, au chanteur John Lennon les paroles de sa chanson Imagine, étant reçu à la Maison-Blanche par trois présidents successifs, participant à la reprise des relations diplomatiques entre la Chine et les États-Unis, révélant à son insu le scandale du Watergate et étant à l'origine de quelques-unes des principales tendances socio-culturelles des années 1980.",
        img: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT0NxVrYdi8Ro5zRnIbewaT_uCOl5_2uhxxyQoU6s9gOfEDovGi'
    }
];

export default movies;